import os
from pathlib import Path
from fontTools.ttLib import TTFont

# Determine module root directory (parent of the scripts folder)
MODULE_ROOT = Path(__file__).resolve().parent.parent

FONTS_DIR = MODULE_ROOT / "static" / "src" / "fonts"
OUTPUT_CSS = MODULE_ROOT / "static" / "src" / "css" / "fonts.css"

# Base URL path for fonts in Odoo
URL_BASE_PATH = "/joo_glyph_fonts/static/src/fonts"

# Fallback font: Standard Odoo CSS variables with generic sans-serif fallback
FALLBACK_FONT = "var(--body-font-family, var(--font-sans-serif, sans-serif))"

# Target font configurations (Set 'default': True to specify the default initial font)
FONT_CONFIGS = [
    {
        "font_family": "DWPIexMincho",
        "file_name": "DWPIexMincho.ttf",
        "default": True,
    },
    {
        "font_family": "DWPIMincho",
        "file_name": "DWPIMincho.ttf",
    },
    {
        "font_family": "IPAmjMincho",
        "file_name": "ipamjm.ttf",
    },
]


def extract_font_names(file_path):
    """Extract font names from a TTF/OTF file for local() CSS declarations."""
    font = TTFont(file_path)
    name_table = font["name"]
    names = []

    # Target nameIDs: 6 (PostScript Name), 4 (Full Name), 1 (Font Family)
    for target_id in (6, 4, 1):
        for record in name_table.names:
            if record.nameID == target_id:
                try:
                    string = record.toUnicode()
                    if string and string not in names:
                        names.append(string)
                except UnicodeDecodeError:
                    continue
    return names


def generate_css():
    """Generate CSS definitions using CSS variables and class selectors for Odoo views."""
    font_faces, class_selectors = [], []

    # Find default font family from FONT_CONFIGS (fallback to first item if not specified)
    default_config = next(
        (cfg for cfg in FONT_CONFIGS if cfg.get("default")), FONT_CONFIGS[0]
    )
    default_family = default_config["font_family"]

    for config in FONT_CONFIGS:
        family = config["font_family"]
        file_name = config["file_name"]
        file_path = FONTS_DIR / file_name
        url_path = f"{URL_BASE_PATH}/{file_name}"

        if not file_path.exists():
            print(f"Warning: {file_path.name} not found. Skipping...")
            continue

        local_names = extract_font_names(file_path)
        local_src_parts = [f'local("{name}")' for name in local_names]
        local_src_str = ",\n         ".join(local_src_parts)

        # 1. @font-face definition
        font_faces.append(f"""@font-face {{
    font-family: "{family}";
    src: {local_src_str},
         url("{url_path}") format("truetype");
}}""")

        # 2. Fixed font class selector
        class_selectors.append(f""".joo-font-{family} {{
    font-family: "{family}", var(--joo-font-fallback) !important;
}}""")

    css_content = f"""/**
 * Font definitions for joo_glyph_fonts module.
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
 * Generated by: scripts/generate_css.py
 */

/* Global Variables */
:root {{
    --joo-font-fallback: {FALLBACK_FONT};
    --joo-font-dynamic: "{default_family}";
}}

/* Font face definitions */
{chr(10).join(font_faces)}


/**
 * 1. Dynamic font class selector
 * Matches elements with the `joo-font` class.
 * Managed dynamically via JS setting --joo-font-dynamic on :root.
 */
.joo-font {{
    font-family: var(--joo-font-dynamic), var(--joo-font-fallback) !important;
}}


/**
 * 2. Fixed font class selectors
 * Specific font class overrides the dynamic .joo-font rule.
 */
{chr(10).join(class_selectors)}
"""

    OUTPUT_CSS.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_CSS.write_text(css_content, encoding="utf-8")
    print(f"CSS successfully generated at: {OUTPUT_CSS}")


if __name__ == "__main__":
    generate_css()
